[package]
name = "exodus"
version = "0.1.0"
authors = ["luozijun <gnulinux@126.com>"]


[workspace]
members = [
    "logging",
    "iana",
    "netif"
]


[[bin]]
name = "vpn"
path = "src/bin/vpn.rs"

[[bin]]
name = "proxy"
path = "src/bin/proxy.rs"

[[bin]]
name = "crypto"
path = "src/crypto.rs"

[dependencies]
logging = { path = "./logging" }
netif = { path = "./netif" }

cfg-if = "0.1"
bitflags = "1.0"
byteorder = "1.2.1"
rand = "0.4.1"
snap = "0.2.3"
openssl = "0.9.23"
mio-more = "0.1.0"
ipnetwork = "0.12"

clap     = { version = "2.29.0", default-features = false, features = [] }
ctrlc    = { version = "3.0.3", default-features = false, features = ["termination"] }
hwaddr   = { version = "0.1.3", default-features = false, features = [] }
futures  = { version = "0.1.17", default-features = false, features = ["use_std"] }
mio      = { version = "0.6.11", default-features = false, features = [] }

[dependencies.smoltcp]
git = "https://github.com/m-labs/smoltcp.git"
branch = "master"
default-features = false
features = [
    "std", "log",
    "proto-ipv4", "proto-ipv6",
    "socket-raw", "socket-icmp", "socket-udp", "socket-tcp"
]

[target.'cfg(unix)'.dependencies.tun]
git = "https://github.com/LuoZijun/rust-tun.git"
branch = "patch-1"
default-features = false
features = ["mio"]

[target.'cfg(unix)'.dependencies.libc]
git = "https://github.com/rust-lang/libc.git"
branch = "master"

[target.'cfg(unix)'.dependencies.nix]
git = "https://github.com/LuoZijun/nix.git"
branch = "patch-4"


[profile.dev]
opt-level = 0
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 3
panic = 'unwind'
incremental = true

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
# codegen-units = 3 # codegen-units ignored with lto=true
panic = 'unwind'
incremental = false
