[package]
name = "proxy"
version = "0.1.0"
authors = ["luozijun <gnulinux@126.com>"]

[[bin]]
name = "socks"
path = "src/ingress/socks.rs"

[[bin]]
name = "dns"
path = "src/dns.rs"

[[bin]]
name = "ifaces"
path = "src/net/interface.rs"

[[bin]]
name = "ssh"
path = "src/egress/ssh.rs"

[[bin]]
name = "timezone"
path = "src/iana/timezone.rs"


[dependencies]
ssh2 = "0.3.2"
trust-dns-resolver = "0.6.0"

log = "0.3"
futures = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"
env_logger = "0.3"
trust-dns = { version = "0.9.2", default-features = false }

chrono = "0.4.0"
chrono-tz = "0.4.1"

nix = "0.9.0"
libc = "0.2.31"