[package]
name = "proxy"
version = "0.1.0"
authors = ["luozijun <gnulinux@126.com>"]

[workspace]
members = [
    "iana",
    "taptun",
    "netpacket",
    "netstack",
    "netfilter",
    "netproxy",
    "nettunnel"
]
