[package]
name = "netstack"
version = "0.1.0"
authors = ["luozijun <gnulinux@126.com>"]

[dependencies]
libc = ">=0.2.34"
logging   = { path = "../logging" }


byteorder = "1.1.0"
socket2   = "0.2.4"

[target.'cfg(unix)'.dependencies]
nix  = "0.9.0"
